# Generated by Django 2.2.1 on 2019-05-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0002_auto_20190519_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('NT', 'Normaltype'), ('RT', 'Redtype')], default='NT', max_length=2),
        ),
    ]
