# Generated by Django 2.2.1 on 2019-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0003_auto_20190519_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
