# Generated by Django 2.2.1 on 2019-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0004_auto_20190520_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='tax_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
