# Generated by Django 2.2.1 on 2019-05-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0005_auto_20190520_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
