# Generated by Django 2.2.1 on 2019-05-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0006_companies_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_source.Products')),
            ],
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='price',
            new_name='total_price_after_vat',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='total',
        ),
        migrations.AddField(
            model_name='transactions',
            name='signed_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactions',
            name='total_price_before_vat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_source.Companies'),
        ),
        migrations.DeleteModel(
            name='Discounts',
        ),
        migrations.AddField(
            model_name='transactionproducts',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_source.Transactions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_products',
            field=models.ManyToManyField(through='web_source.TransactionProducts', to='web_source.Products'),
        ),
    ]
