# Generated by Django 2.2.1 on 2019-05-30 14:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0007_auto_20190526_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
