# Generated by Django 2.2.1 on 2019-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0008_companies_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='work_phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
