# Generated by Django 2.2.1 on 2019-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0009_companies_work_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='address_transport',
            field=models.TextField(default=''),
        ),
    ]
